trigger:
  - main

variables:
  imageName: automation
  imageTag: v2
  dockerImage: yogeshwar001.azurecr.io/auotmation:v2

stages:
- stage: build
  displayName: build and push image
  jobs:
  - job: build and push
    pool:
     vmImage 'ubuntu-latest'
    steps:
    - checkout: self
    - task: Docker@2
      displayName: build and push docker image
      inputs:
        containerRegistry: yogeshwar001
        repository: automation
        command: buildAndPush
        Dockerfile: ./
        tags: |
          automation:v2

- stage: deploy
  displayName: deploy to aks
  dependsOn: build
  jobs:
  - job: deploy
    Pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
      - task: DownloadSecureFile@1
        displayName: GetKubeConfig
        inputs:
          secureFile: KubeConfig
      - script: 
          mkdir -p ~/kube
          mv $(GetKubeConfig.secureFilePath) ~/kube/config
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          displayName: kubectl apply