apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automation
  template:
    metadata:
      labels:
        app: automation
    spec:
      containers:
      - name: automation
        image: yogeshwar001.azurecr.io/automation:$(Build.BuildId)
        ports:
        - containerPort: 80
